package com.ecommerce.commerce_service.exception;
public enum ErrorCode {
 INVALID_ACCESS_TOKEN, AUTHORIZATION_SERVICE_UNAVAILABLE, ACCOUNT_DISABLED, ACCOUNT_LOCKED,
 ACCESS_DENIED, VALIDATION_ERROR, INTERNAL_ERROR, INVALID_IDEMPOTENCY_KEY, DUPLICATE_REQUEST,
 RATE_LIMIT_EXCEEDED, CATALOG_UNAVAILABLE, PRODUCT_UNAVAILABLE, DUPLICATE_ORDER_ITEM,
 ORDER_NOT_FOUND, RESOURCE_NOT_OWNED, INVALID_ORDER_STATE, PAYMENT_ALREADY_PROCESSED,
 INVOICE_NOT_FOUND, INVALID_PROMOTION, CONCURRENT_MODIFICATION, INVALID_PROMOTION_DATES, PROMOTION_ALREADY_EXISTS
}
