package com.ecommerce.catalog_service.exception;
public enum ErrorCode {
    PRODUCT_NOT_FOUND, PRODUCT_SKU_ALREADY_EXISTS, PRODUCT_ALREADY_ACTIVE, PRODUCT_ALREADY_INACTIVE,
    INVALID_ACCESS_TOKEN, AUTHORIZATION_SERVICE_UNAVAILABLE, ACCOUNT_DISABLED, ACCOUNT_LOCKED,
    ACCESS_DENIED, VALIDATION_ERROR, INTERNAL_ERROR, CONCURRENT_MODIFICATION, INSUFFICIENT_STOCK,
    INVALID_INVENTORY_OPERATION, INVALID_IDEMPOTENCY_KEY, DUPLICATE_REQUEST, RATE_LIMIT_EXCEEDED
}
