name: OWASP ZAP Baseline Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Escaneo Dinámico con ZAP
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      # 1. Levantar la infraestructura usando la carpeta backend como raíz del comando
# 1. Forzar el cambio de directorio y compilar explícitamente desde ahí
      - name: Levantar la App
        run: |
          cd backend
          pwd
          docker compose up -d
          sleep 30
          
      # 2. Ejecuta el escáner dinámico apuntando a tu localhost o contenedor
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost:3000' # Cambia esto por el puerto de tu app
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_title: 'Alerta de Seguridad Encontrada por ZAP'
